### ISSUE TITLE
Support indented heredoc string variant that is introduced by the <<- sequence

### ISSUE THREAD

**Issue by mark-greene** [cmur2/language-terraform#47]
Terraform accepts an indented heredoc string variant that is introduced by the <<- sequence.
```
block {
  value = <<-EOT
  hello
    world
  EOT
}
```
https://www.terraform.io/docs/configuration/expressions.html#string-literals

I saw this was added in 1.9.3 but it is not working for me.  Do I need to remove / reinstall?

![terraform](https://user-images.githubusercontent.com/4949362/81693857-8e001d00-942e-11ea-8000-bdfb1a94d4ba.png)

**Comment by mark-greene** [comment]
`end: '^\\s*?(\\1)$'` seems to fix it.

**Comment by cmur2** [comment]
You gave the example (note the 2-spaces indention before the closing `EOT`) which works fine for me in v0.9.3:
```
block {
  value = <<-EOT
  hello
    world
  EOT
}
```

@mark-greene In your screenshot though it looks like the closing EOT is not indented? This would match to the example (notice the opening `<<EOT` instead of `<<-EOT`) which also works fine in v0.9.3:
```
block {
  value = <<EOT
hello
world
EOT
}
```
